//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alobodo.
        /// </summary>
        public static string Alobodo {
            get {
                return ResourceManager.GetString("Alobodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Universal platform for mobile services.
        /// </summary>
        public static string AlobodoSubTitle {
            get {
                return ResourceManager.GetString("AlobodoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doris Bank.
        /// </summary>
        public static string Doris {
            get {
                return ResourceManager.GetString("Doris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated system of financial services.
        /// </summary>
        public static string DorisSubTitle {
            get {
                return ResourceManager.GetString("DorisSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimedi.
        /// </summary>
        public static string Elimedi {
            get {
                return ResourceManager.GetString("Elimedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your health goddess.
        /// </summary>
        public static string ElimediSubTitle {
            get {
                return ResourceManager.GetString("ElimediSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahmadi.ali2219@gmail.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string error404 {
            get {
                return ResourceManager.GetString("error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t seem to find the page &lt;br&gt; you are looking for :(.
        /// </summary>
        public static string error404text {
            get {
                return ResourceManager.GetString("error404text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Buddy.
        /// </summary>
        public static string heyBuddy {
            get {
                return ResourceManager.GetString("heyBuddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC.
        /// </summary>
        public static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated authentication system.
        /// </summary>
        public static string MacSubTitle {
            get {
                return ResourceManager.GetString("MacSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone nember functions.
        /// </summary>
        public static string PhoneNumberFunctions {
            get {
                return ResourceManager.GetString("PhoneNumberFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A library for controlling phone numbers.
        /// </summary>
        public static string PhoneNumberFunctionsSubTitle {
            get {
                return ResourceManager.GetString("PhoneNumberFunctionsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raya.
        /// </summary>
        public static string Raya {
            get {
                return ResourceManager.GetString("Raya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology design and manufacturing service provider.
        /// </summary>
        public static string RayaSubTitle {
            get {
                return ResourceManager.GetString("RayaSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
    }
}
