//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alobodo.
        /// </summary>
        public static string Alobodo {
            get {
                return ResourceManager.GetString("Alobodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Universal platform for mobile services.
        /// </summary>
        public static string AlobodoSubTitle {
            get {
                return ResourceManager.GetString("AlobodoSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular.
        /// </summary>
        public static string Angular {
            get {
                return ResourceManager.GetString("Angular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asp.Net .
        /// </summary>
        public static string Aspnetcore {
            get {
                return ResourceManager.GetString("Aspnetcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora.
        /// </summary>
        public static string Aurora {
            get {
                return ResourceManager.GetString("Aurora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Product Collection, A Store For Selling Satin Sleep Products.
        /// </summary>
        public static string Aurora_Des {
            get {
                return ResourceManager.GetString("Aurora_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVR.
        /// </summary>
        public static string AVR {
            get {
                return ResourceManager.GetString("AVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap.
        /// </summary>
        public static string Bootsrap {
            get {
                return ResourceManager.GetString("Bootsrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++.
        /// </summary>
        public static string CPlus {
            get {
                return ResourceManager.GetString("CPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Sharp.
        /// </summary>
        public static string Csharp {
            get {
                return ResourceManager.GetString("Csharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string Css {
            get {
                return ResourceManager.GetString("Css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLMS.
        /// </summary>
        public static string DLMS {
            get {
                return ResourceManager.GetString("DLMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker.
        /// </summary>
        public static string Docker {
            get {
                return ResourceManager.GetString("Docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doris Bank.
        /// </summary>
        public static string Doris {
            get {
                return ResourceManager.GetString("Doris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated system of financial services.
        /// </summary>
        public static string DorisSubTitle {
            get {
                return ResourceManager.GetString("DorisSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elimedi.
        /// </summary>
        public static string Elimedi {
            get {
                return ResourceManager.GetString("Elimedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your health goddess.
        /// </summary>
        public static string ElimediSubTitle {
            get {
                return ResourceManager.GetString("ElimediSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahmadi.ali2219@gmail.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        public static string EnListening {
            get {
                return ResourceManager.GetString("EnListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string EnReading {
            get {
                return ResourceManager.GetString("EnReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking.
        /// </summary>
        public static string EnSpeaking {
            get {
                return ResourceManager.GetString("EnSpeaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string EnWriting {
            get {
                return ResourceManager.GetString("EnWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string error404 {
            get {
                return ResourceManager.GetString("error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t seem to find the page &lt;br&gt; you are looking for :(.
        /// </summary>
        public static string error404text {
            get {
                return ResourceManager.GetString("error404text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelancer.
        /// </summary>
        public static string Freelancer {
            get {
                return ResourceManager.GetString("Freelancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start my career as a freelancer with two project, Knight Shop Website and Game Club Application.
        /// </summary>
        public static string Freelancer_Des {
            get {
                return ResourceManager.GetString("Freelancer_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019 -2019.
        /// </summary>
        public static string Freelancer_Year {
            get {
                return ResourceManager.GetString("Freelancer_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Git {
            get {
                return ResourceManager.GetString("Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Buddy.
        /// </summary>
        public static string heyBuddy {
            get {
                return ResourceManager.GetString("heyBuddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Server 4.
        /// </summary>
        public static string Identityserver4 {
            get {
                return ResourceManager.GetString("Identityserver4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript.
        /// </summary>
        public static string Javascript {
            get {
                return ResourceManager.GetString("Javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior Web Developer.
        /// </summary>
        public static string Junior {
            get {
                return ResourceManager.GetString("Junior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I join &quot;Medis Holding&quot; as Junior backend developer and we rewrite Alobodo project .
        /// </summary>
        public static string Junior_Des {
            get {
                return ResourceManager.GetString("Junior_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020 - 2021.
        /// </summary>
        public static string Junior_Year {
            get {
                return ResourceManager.GetString("Junior_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC.
        /// </summary>
        public static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated authentication system.
        /// </summary>
        public static string MacSubTitle {
            get {
                return ResourceManager.GetString("MacSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MongoDB.
        /// </summary>
        public static string Mongo {
            get {
                return ResourceManager.GetString("Mongo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone nember functions.
        /// </summary>
        public static string PhoneNumberFunctions {
            get {
                return ResourceManager.GetString("PhoneNumberFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A library for controlling phone numbers.
        /// </summary>
        public static string PhoneNumberFunctionsSubTitle {
            get {
                return ResourceManager.GetString("PhoneNumberFunctionsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postman.
        /// </summary>
        public static string PostMan {
            get {
                return ResourceManager.GetString("PostMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raya.
        /// </summary>
        public static string Raya {
            get {
                return ResourceManager.GetString("Raya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology design and manufacturing service provider.
        /// </summary>
        public static string RayaSubTitle {
            get {
                return ResourceManager.GetString("RayaSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React.
        /// </summary>
        public static string React {
            get {
                return ResourceManager.GetString("React", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redis.
        /// </summary>
        public static string Redis {
            get {
                return ResourceManager.GetString("Redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium.
        /// </summary>
        public static string Selenium {
            get {
                return ResourceManager.GetString("Selenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Web Developer.
        /// </summary>
        public static string Senior {
            get {
                return ResourceManager.GetString("Senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I continue my work as a senior web developer by continuing to work in Medis Holding and doing many projects in different fields..
        /// </summary>
        public static string Senior_Des {
            get {
                return ResourceManager.GetString("Senior_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022 - Now.
        /// </summary>
        public static string Senior_Year {
            get {
                return ResourceManager.GetString("Senior_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignalR.
        /// </summary>
        public static string SignalR {
            get {
                return ResourceManager.GetString("SignalR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Industrial Management Institute.
        /// </summary>
        public static string SIMI {
            get {
                return ResourceManager.GetString("SIMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaned C# Language.
        /// </summary>
        public static string SIMI_Des {
            get {
                return ResourceManager.GetString("SIMI_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned Asp.Net Core Framework and SQL Server.
        /// </summary>
        public static string SIMI_Des1 {
            get {
                return ResourceManager.GetString("SIMI_Des1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned Xamarin Framework.
        /// </summary>
        public static string SIMI_Des2 {
            get {
                return ResourceManager.GetString("SIMI_Des2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-2018.
        /// </summary>
        public static string SIMI_Year {
            get {
                return ResourceManager.GetString("SIMI_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018-2019.
        /// </summary>
        public static string SIMI_Year1 {
            get {
                return ResourceManager.GetString("SIMI_Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019-2019.
        /// </summary>
        public static string SIMI_Year2 {
            get {
                return ResourceManager.GetString("SIMI_Year2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSQL Server.
        /// </summary>
        public static string SQL {
            get {
                return ResourceManager.GetString("SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQlite.
        /// </summary>
        public static string Sqlite {
            get {
                return ResourceManager.GetString("Sqlite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swagger.
        /// </summary>
        public static string Swagger {
            get {
                return ResourceManager.GetString("Swagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Test.
        /// </summary>
        public static string UnitTest {
            get {
                return ResourceManager.GetString("UnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamedan University of Technology.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor of Science in Electrical Engineering-Control.
        /// </summary>
        public static string University_Des {
            get {
                return ResourceManager.GetString("University_Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011-2015.
        /// </summary>
        public static string University_Year {
            get {
                return ResourceManager.GetString("University_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Api.
        /// </summary>
        public static string Webapi {
            get {
                return ResourceManager.GetString("Webapi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.
        /// </summary>
        public static string Xamarin {
            get {
                return ResourceManager.GetString("Xamarin", resourceCulture);
            }
        }
    }
}
